version: '3'

services:
  mariadb:
    # build: ./requirements/mariadb
    image: mariadb:10.5
    container_name: mariadb
    restart: always
    volumes:
      - ./requirements/mariadb/tools:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: skim1234
      MYSQL_DATABASE: wordpress
      MYSQL_USER: skim
      MYSQL_PASSWORD: skim1234

  wordpress:
    build: ./requirements/wordpress
    # image: wordpress:php7.3-fpm-alpine
    volumes:
      - wp_index:/var/www/html
    container_name: wordpress
    restart: always
    depends_on:
      - mariadb
    links:
      - mariadb
    environment:
      MYSQL_ROOT_PASSWORD: skim1234
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: skim
      WORDPRESS_DB_PASSWORD: skim1234
      WORDPRESS_TABLE_PREFIX: wp_

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    restart: always
    volumes:
      - wp_index:/var/www/html
    links:
      - wordpress
    ports:
      - 443:443

volumes:
  wp_index:

